// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzsz7qMpkg4xP9DXOjNtIZubb_kjINrE',
    appId: '1:598922521405:web:b62258cec1cf09373f7354',
    messagingSenderId: '598922521405',
    projectId: 'danielgutierreztorres-recall',
    authDomain: 'danielgutierreztorres-recall.firebaseapp.com',
    storageBucket: 'danielgutierreztorres-recall.firebasestorage.app',
    measurementId: 'G-MCPX4ZJ60T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60RnpBSwen3shr0sFJX7T5jz5trgTC2o',
    appId: '1:598922521405:android:d1aee9db63b7b9dc3f7354',
    messagingSenderId: '598922521405',
    projectId: 'danielgutierreztorres-recall',
    storageBucket: 'danielgutierreztorres-recall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UwCmkxZbU_Fo9ZgvpbY0adlJgaQ7Vf8',
    appId: '1:598922521405:ios:dbbae94002261c573f7354',
    messagingSenderId: '598922521405',
    projectId: 'danielgutierreztorres-recall',
    storageBucket: 'danielgutierreztorres-recall.firebasestorage.app',
    iosBundleId: 'com.example.danelgutierreztorrespruebatecnicaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UwCmkxZbU_Fo9ZgvpbY0adlJgaQ7Vf8',
    appId: '1:598922521405:ios:dbbae94002261c573f7354',
    messagingSenderId: '598922521405',
    projectId: 'danielgutierreztorres-recall',
    storageBucket: 'danielgutierreztorres-recall.firebasestorage.app',
    iosBundleId: 'com.example.danelgutierreztorrespruebatecnicaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzsz7qMpkg4xP9DXOjNtIZubb_kjINrE',
    appId: '1:598922521405:web:7c201fdef9e49cb23f7354',
    messagingSenderId: '598922521405',
    projectId: 'danielgutierreztorres-recall',
    authDomain: 'danielgutierreztorres-recall.firebaseapp.com',
    storageBucket: 'danielgutierreztorres-recall.firebasestorage.app',
    measurementId: 'G-T56FHN9G36',
  );
}
